# Find Hardware Support
# Detects available hardware features on the target system

# GPIO Support
if(ENABLE_GPIO)
    find_path(GPIO_INCLUDE_DIR NAMES bcm2712.h PATHS /usr/include /usr/local/include)
    if(GPIO_INCLUDE_DIR)
        set(GPIO_FOUND TRUE)
        message(STATUS "Found GPIO support")
    else()
        message(WARNING "GPIO support not found")
    endif()
endif()

# UART Support
if(ENABLE_UART)
    find_path(UART_INCLUDE_DIR NAMES termios.h PATHS /usr/include)
    if(UART_INCLUDE_DIR)
        set(UART_FOUND TRUE)
        message(STATUS "Found UART support")
    else()
        message(WARNING "UART support not found")
    endif()
endif()

# I2C Support
if(ENABLE_I2C)
    find_path(I2C_INCLUDE_DIR NAMES linux/i2c-dev.h PATHS /usr/include)
    if(I2C_INCLUDE_DIR)
        set(I2C_FOUND TRUE)
        message(STATUS "Found I2C support")
    else()
        message(WARNING "I2C support not found")
    endif()
endif()

# SPI Support
if(ENABLE_SPI)
    find_path(SPI_INCLUDE_DIR NAMES linux/spi/spidev.h PATHS /usr/include)
    if(SPI_INCLUDE_DIR)
        set(SPI_FOUND TRUE)
        message(STATUS "Found SPI support")
    else()
        message(WARNING "SPI support not found")
    endif()
endif()

# Camera Support (V4L2)
if(ENABLE_CAMERA)
    find_path(V4L2_INCLUDE_DIR NAMES linux/videodev2.h PATHS /usr/include)
    find_library(V4L2_LIBRARY NAMES v4l2)
    if(V4L2_INCLUDE_DIR AND V4L2_LIBRARY)
        set(V4L2_FOUND TRUE)
        message(STATUS "Found V4L2 camera support")
    else()
        message(WARNING "V4L2 camera support not found")
    endif()
endif()

# Audio Support (ALSA)
if(ENABLE_AUDIO)
    find_path(ALSA_INCLUDE_DIR NAMES alsa/asoundlib.h PATHS /usr/include)
    find_library(ALSA_LIBRARY NAMES asound)
    if(ALSA_INCLUDE_DIR AND ALSA_LIBRARY)
        set(ALSA_FOUND TRUE)
        message(STATUS "Found ALSA audio support")
    else()
        message(WARNING "ALSA audio support not found")
    endif()
endif()

# PCIe Support
if(ENABLE_PCIE)
    find_path(PCIe_INCLUDE_DIR NAMES pci/pci.h PATHS /usr/include)
    find_library(PCIe_LIBRARY NAMES pci)
    if(PCIe_INCLUDE_DIR AND PCIe_LIBRARY)
        set(PCIe_FOUND TRUE)
        message(STATUS "Found PCIe support")
    else()
        message(WARNING "PCIe support not found")
    endif()
endif()

# Package summary
message(STATUS "Hardware Support Summary:")
message(STATUS "  GPIO: ${GPIO_FOUND}")
message(STATUS "  UART: ${UART_FOUND}")
message(STATUS "  I2C: ${I2C_FOUND}")
message(STATUS "  SPI: ${SPI_FOUND}")
message(STATUS "  V4L2: ${V4L2_FOUND}")
message(STATUS "  ALSA: ${ALSA_FOUND}")
message(STATUS "  PCIe: ${PCIe_FOUND}")
